name: dev deployment
on:
  # Runs on push to the develop branch
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5   
      redis:
        image: redis/redis-stack-server:latest
        ports:
          - 6379:6379
    env:
      DB_HOST: localhost
      DB_USER: test
      DB_PASS: test
      DB_PORT: "5432"
      DB: test
      ACCESS_TOKEN_SECRET: 27219441075f8cbcc77b578
      REFRESH_TOKEN_SECRET: c5bd3f757952747f4a64a31a
      JWT_REFRESH_EXPIRATION: 7000
    steps:
      - uses: actions/checkout@v2
      # setup the node development environment
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install all dependencies
        run: npm install
      # run after PR merge
      - name: Run tests and generate coverage
        run: npm run coverage
      - name: Check linting errors
        run: npm run lint
  