name: CI
on:
  # Triggers the workflow on push for all branches
  push:
  # Triggers the workflow on pull request on the develop and main branch
  pull_request:
    branches:
      - main
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis/redis-stack-server:latest
        ports:
          - 6379:6379
    concurrency: test_environment
    env:
      DB_HOST: localhost
      DB_USER: test
      DB_PASS: test
      DB_PORT: "5432"
      DB: test
      ACCESS_TOKEN_SECRET: 27219441075f8cbcc77b578
      REFRESH_TOKEN_SECRET: c5bd3f757952747f4a64a31a
      JWT_REFRESH_EXPIRATION: 7000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install all dependencies
        run: npm install
      - name: Check linting errors
        run: npm run lint
      - name: Run tests and generate coverage reports
        run: npm run coverage
      - name: Sending coveralls report
        uses: coverallsapp/github-action@master
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to codeclimate
        uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_REPORTER_ID}}
